### ISSUE TITLE
Missing trailing newline

### ISSUE THREAD

**Issue by bartekpacia** [invertase/spec#13]
I use `zsh`. The `%` at the end of `spec` output means that [it does not end with a newline](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

<img width="486" alt="Screenshot 2022-02-03 at 3 47 57 PM" src="https://user-images.githubusercontent.com/40357511/152365829-44df2e59-2fb2-47a4-a797-9806ed4c2daf.png">

**Comment by Ehesp** [comment]
Haha... We were wondering what was causing that. Thanks for reporting and explaining.

**Comment by bartekpacia** [comment]
Shouldn't this be fixed?

**Comment by Salakar** [comment]
Fix now available in `v0.1.0+1` thanks
