### ISSUE TITLE
Support `dart pub global run spec_cli`

### ISSUE THREAD

**Issue by spydon** [invertase/spec#22]
Today when running Spec from somewhere where you don't have the installed dart packages on your path (like in cicd) you have to run:
```sh
dart pub global run spec_cli:main
```
It would be nice if it could support running:
```sh
dart pub global run spec_cli
```
Just like with Melos.

**Comment by isaacadariku** [comment]
@mhadaily @Salakar Please I will like to take this

**Comment by rrousselGit** [comment]
The syntax is `dart pub global run spec`
