### ISSUE TITLE
Will be adding dark mode to this page.

### ISSUE THREAD

**Issue by Anikalp1** [invertase/spec#37]
Hey, I will be adding dark mode to this page. 
Kindly assign this task to me.

**Comment by rrousselGit** [comment]
Dart mode to what exactly?

**Comment by Anikalp1** [comment]
To page, as it is only in light mode.
Let me attach an example: 

LIGHT MODE 
![Screenshot (90)](https://user-images.githubusercontent.com/96365444/193866717-4c1640d4-8c08-4267-925f-9575a95bceea.png)

DARK MODE
![Screenshot (91)](https://user-images.githubusercontent.com/96365444/193866794-eae22e01-3401-4699-af63-fda302f7ad97.png)

**Comment by Ehesp** [comment]
@Anikalp1 Sorry what relevance does that have to spec?
